//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessUniversity.Helper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccessUniversity.Helper.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Semester 2, 2020 and the IAB330 - Mobile Application Development unit!
        ///
        ///We would like to welcome you to IAB330 Mobile Application Development this semester. 
        ///Please check out the &apos;Getting Started&apos;, &apos;weekly schedule&apos; and &apos;week 1&apos; folders which provides important information for the unit. 
        ///Kind regards,
        ///
        ///Sri (Co-Unit Coordinator/Lecturer)
        ///Trina (Co-Unit coordinator)
        ///Josh (Tutor).
        /// </summary>
        internal static string AnnouncementMessage {
            get {
                return ResourceManager.GetString("AnnouncementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements.
        /// </summary>
        internal static string AnnouncementTitle {
            get {
                return ResourceManager.GetString("AnnouncementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment.
        /// </summary>
        internal static string Assessment {
            get {
                return ResourceManager.GetString("Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment 01.
        /// </summary>
        internal static string Assessment_01 {
            get {
                return ResourceManager.GetString("Assessment_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment 02.
        /// </summary>
        internal static string Assessment_02 {
            get {
                return ResourceManager.GetString("Assessment_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment 03.
        /// </summary>
        internal static string Assessment_03 {
            get {
                return ResourceManager.GetString("Assessment_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment 1 
        ///This assessment task requires you to investigate a problem space and create a report that explains the need for and design of a mobile application.
        ///Please note that assessment 1 will form the basis for assessment 2.
        ///
        ///Last updated: 11/08/2020
        ///Changelog
        ///
        ///Video added
        ///Teamwork criteria has been explicitly stated in the CRA.
        /// </summary>
        internal static string Assessment_Content {
            get {
                return ResourceManager.GetString("Assessment_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAB303 - Assessment.
        /// </summary>
        internal static string AssessmentPage_Title {
            get {
                return ResourceManager.GetString("AssessmentPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents Page.
        /// </summary>
        internal static string Contents_Page {
            get {
                return ResourceManager.GetString("Contents Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the language change the language settings of the device.
        /// </summary>
        internal static string ContentsPage_Alert {
            get {
                return ResourceManager.GetString("ContentsPage_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lectures.
        /// </summary>
        internal static string ContentsPage_Lectures {
            get {
                return ResourceManager.GetString("ContentsPage_Lectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string ContentsPage_Support {
            get {
                return ResourceManager.GetString("ContentsPage_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAB303 - Contents.
        /// </summary>
        internal static string ContentsPage_Title {
            get {
                return ResourceManager.GetString("ContentsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics.
        /// </summary>
        internal static string ContentsPage_Topics {
            get {
                return ResourceManager.GetString("ContentsPage_Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheets.
        /// </summary>
        internal static string ContentsPage_Worksheets {
            get {
                return ResourceManager.GetString("ContentsPage_Worksheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string ContentsPageDetail {
            get {
                return ResourceManager.GetString("ContentsPageDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAB330 Mobile Application Development Week 1.
        /// </summary>
        internal static string ContentsPageDetail_FileName {
            get {
                return ResourceManager.GetString("ContentsPageDetail_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency.
        /// </summary>
        internal static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eStudent.
        /// </summary>
        internal static string eStudent {
            get {
                return ResourceManager.GetString("eStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Simplified.
        /// </summary>
        internal static string Language_ChineseSimplified {
            get {
                return ResourceManager.GetString("Language_ChineseSimplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Traditional.
        /// </summary>
        internal static string Language_ChineseTraditional {
            get {
                return ResourceManager.GetString("Language_ChineseTraditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string Language_French {
            get {
                return ResourceManager.GetString("Language_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string Language_German {
            get {
                return ResourceManager.GetString("Language_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindi.
        /// </summary>
        internal static string Language_Hindi {
            get {
                return ResourceManager.GetString("Language_Hindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian.
        /// </summary>
        internal static string Language_Indonesian {
            get {
                return ResourceManager.GetString("Language_Indonesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string Language_Japanese {
            get {
                return ResourceManager.GetString("Language_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        internal static string Language_Korean {
            get {
                return ResourceManager.GetString("Language_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string Language_Portuguese {
            get {
                return ResourceManager.GetString("Language_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string Language_Russian {
            get {
                return ResourceManager.GetString("Language_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string Language_Spanish {
            get {
                return ResourceManager.GetString("Language_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture Video.
        /// </summary>
        internal static string Lecture_Video {
            get {
                return ResourceManager.GetString("Lecture Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed, username or passsword incorrect..
        /// </summary>
        internal static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successful.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OkConfirmation {
            get {
                return ResourceManager.GetString("OkConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted Text.
        /// </summary>
        internal static string PDFViewer_ExpanderLabel {
            get {
                return ResourceManager.GetString("PDFViewer_ExpanderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Extracted.
        /// </summary>
        internal static string PDFViewer_NotExtracted {
            get {
                return ResourceManager.GetString("PDFViewer_NotExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Page No.
        /// </summary>
        internal static string PDFViewer_PageNoEntry {
            get {
                return ResourceManager.GetString("PDFViewer_PageNoEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string PDFViewer_Picker {
            get {
                return ResourceManager.GetString("PDFViewer_Picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Content.
        /// </summary>
        internal static string UnitContent {
            get {
                return ResourceManager.GetString("UnitContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID or Email.
        /// </summary>
        internal static string UsernameText {
            get {
                return ResourceManager.GetString("UsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the URL here.
        /// </summary>
        internal static string videoURL {
            get {
                return ResourceManager.GetString("videoURL", resourceCulture);
            }
        }
    }
}
